## Importing necessary libraries

In [2]:
import pandas as pd
import requests
import numpy as np

#### Here, we are fetching data from NASA's small-body database
#### Since this API has 1574509 data, we are only importing few of it for the test

In [3]:
url = "https://ssd-api.jpl.nasa.gov/sbdb_query.api"

params = {
    "fields": "spkid,full_name,class,neo,pha,orbit_id,epoch,e,a,q,i,om,w,ma,moid,H,diameter,albedo,rot_per,spec_T,spec_B",
    "limit": 1500
}

response = requests.get(url, params=params)

response.status_code

200

#### the status code of 200 represents success

#### now we will store the reponses from the API in the data variable

In [6]:
#### commenting below cell, out for readibility of the code, as the data is already fetched and saved in a csv file
#### if not commented, this code will generate huge output in the notebook, which is not ideal for readability

data= response.json()
# print(data)

In [8]:
data.keys()

dict_keys(['signature', 'fields', 'data', 'count'])

#### since the fetched data is in JSON format, we can view the headers using keys

In [9]:
data["fields"]

['spkid',
 'full_name',
 'class',
 'neo',
 'pha',
 'orbit_id',
 'epoch',
 'e',
 'a',
 'q',
 'i',
 'om',
 'w',
 'ma',
 'moid',
 'H',
 'diameter',
 'albedo',
 'rot_per',
 'spec_T',
 'spec_B']

#### for easier understanding, i am planning to rename the columns

In [10]:
new_names = ["spkid", "full_name", "class", "neo_flag", "pha_flag", "orbit_id", "epoch", "eccentricity", "semimajor_axis", "perihelion_distance", "inclination", "longitude_of_ascending_node", "argument_of_perihelion", "mean_anomaly", "minimum_orbit_intersection_distance", "absolute_magnitude", "diameter", "albedo", "rotation_period", "spectral_type_T", "spectral_type_B"]

#### once assessed, i have stored the response in the form of df using the new_names that i have assigned

In [11]:
df = pd.DataFrame(data["data"], columns=new_names)

In [12]:
df.head()

,spkid,full_name,class,neo_flag,pha_flag,orbit_id,epoch,eccentricity,semimajor_axis,perihelion_distance,...,longitude_of_ascending_node,argument_of_perihelion,mean_anomaly,minimum_orbit_intersection_distance,absolute_magnitude,diameter,albedo,rotation_period,spectral_type_T,spectral_type_B
0,20000001,1 Ceres (A801 AA),MBA,N,N,48,2461200.5,0.0797,2.766,2.545,...,80.25,73.29,274.42,1.58,3.34,939.4,0.090,9.074170,G,C
1,20000002,2 Pallas (A802 FA),MBA,N,N,JPL 74,2461200.5,0.2307,2.77,2.131,...,172.89,310.97,254.25,1.23,4.12,513,0.155,7.8132214,B,B
2,20000003,3 Juno (A804 RA),MBA,N,N,JPL 144,2461200.5,0.2557,2.671,1.988,...,169.81,247.90,262.73,1.04,5.19,246.596,0.214,7.21,S,Sk
3,20000004,4 Vesta (A807 FA),MBA,N,N,36,2461200.5,0.0902,2.361,2.148,...,103.70,151.47,81.19,1.14,3.25,522.77,0.4228,5.3421276322,V,V
4,20000005,5 Astraea (A845 XA),MBA,N,N,147,2461200.5,0.1876,2.577,2.093,...,141.45,359.38,181.48,1.11,6.95,106.699,0.274,16.806,S,S

In [13]:
df.columns

Index(['spkid', 'full_name', 'class', 'neo_flag', 'pha_flag', 'orbit_id',
       'epoch', 'eccentricity', 'semimajor_axis', 'perihelion_distance',
       'inclination', 'longitude_of_ascending_node', 'argument_of_perihelion',
       'mean_anomaly', 'minimum_orbit_intersection_distance',
       'absolute_magnitude', 'diameter', 'albedo', 'rotation_period',
       'spectral_type_T', 'spectral_type_B'],
      dtype='str')

In [14]:
df["spkid"].value_counts().sum()

np.int64(1500)

#### few preprocessing steps

In [15]:
df.shape

(1500, 21)

#### the data is actually huge, thus; for now there are only 1500 records with 21 features to look forward to

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   spkid                                1500 non-null   int64
 1   full_name                            1500 non-null   str
 2   class                                1500 non-null   str
 3   neo_flag                             1500 non-null   str
 4   pha_flag                             1500 non-null   str
 5   orbit_id                             1500 non-null   str
 6   epoch                                1500 non-null   str
 7   eccentricity                         1500 non-null   str
 8   semimajor_axis                       1500 non-null   str
 9   perihelion_distance                  1500 non-null   str
 10  inclination                          1500 non-null   str
 11  longitude_of_ascending_node          1500 non-null   str
 12  argument_of_perihelion               1500 non-null   str
 13  mean_anomaly                         1500 non-null   str
 14  minimum_orbit_intersection_distance  1500 non-null   str
 15  absolute_magnitude                   1500 non-null   str
 16  diameter                             1474 non-null   str
 17  albedo                               1472 non-null   str
 18  rotation_period                      1484 non-null   str
 19  spectral_type_T                      808 non-null    str
 20  spectral_type_B                      622 non-null    str
dtypes: int64(1), str(20)
memory usage: 246.2 KB

##### info gives us basic overview of the data

### Important obs: except the spkid, every-other numeric column is also in object form; this should be noted for type conversion

In [17]:
df.describe(include="all")

,spkid,full_name,class,neo_flag,pha_flag,orbit_id,epoch,eccentricity,semimajor_axis,perihelion_distance,...,longitude_of_ascending_node,argument_of_perihelion,mean_anomaly,minimum_orbit_intersection_distance,absolute_magnitude,diameter,albedo,rotation_period,spectral_type_T,spectral_type_B
count,1.500000e+03,1500,1500,1500,1500,1500,1500,1500,1500,1500,...,1500,1500,1500,1500,1500,1474,1472,1484,808,622
unique,NaN,1500,7,2,1,190,1,1152,805,966,...,1469,1476,1460,348,558,1465,519,1455,105,24
top,NaN,1 Ceres (A801 AA),MBA,N,N,JPL 76,2461200.5,0.0828,3.013,2.733,...,125.47,69.63,346.88,1.04,10.04,98,0.044,6.15,S,S
freq,NaN,1,1344,1495,1500,80,1500,5,8,5,...,2,3,2,19,13,2,22,3,282,150
mean,2.000075e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4.331570e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.000000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.000038e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.000075e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.000113e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.000150e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### As most of the numeric variables are also categorized as object, describe doesn't say much
#### We will convert them into int later on

In [18]:
df.isnull().sum()

spkid                                    0
full_name                                0
class                                    0
neo_flag                                 0
pha_flag                                 0
orbit_id                                 0
epoch                                    0
eccentricity                             0
semimajor_axis                           0
perihelion_distance                      0
inclination                              0
longitude_of_ascending_node              0
argument_of_perihelion                   0
mean_anomaly                             0
minimum_orbit_intersection_distance      0
absolute_magnitude                       0
diameter                                26
albedo                                  28
rotation_period                         16
spectral_type_T                        692
spectral_type_B                        878
dtype: int64

#### diameter, albedo, and rotation period have few null values, which can be imputed (if possible with formula) 
#### or can be marked as 0 as they are in small number

#### spectray_type_T and spectral_type_B have comparatively huge proportion of null values

## Handling the DataTypes

#### as mentioned several numeric figures are in object type, thus, we can't manipulate them

In [19]:
df.head(10)

,spkid,full_name,class,neo_flag,pha_flag,orbit_id,epoch,eccentricity,semimajor_axis,perihelion_distance,...,longitude_of_ascending_node,argument_of_perihelion,mean_anomaly,minimum_orbit_intersection_distance,absolute_magnitude,diameter,albedo,rotation_period,spectral_type_T,spectral_type_B
0,20000001,1 Ceres (A801 AA),MBA,N,N,48,2461200.5,0.0797,2.766,2.545,...,80.25,73.29,274.42,1.58,3.34,939.4,0.090,9.074170,G,C
1,20000002,2 Pallas (A802 FA),MBA,N,N,JPL 74,2461200.5,0.2307,2.77,2.131,...,172.89,310.97,254.25,1.23,4.12,513,0.155,7.8132214,B,B
2,20000003,3 Juno (A804 RA),MBA,N,N,JPL 144,2461200.5,0.2557,2.671,1.988,...,169.81,247.90,262.73,1.04,5.19,246.596,0.214,7.21,S,Sk
3,20000004,4 Vesta (A807 FA),MBA,N,N,36,2461200.5,0.0902,2.361,2.148,...,103.70,151.47,81.19,1.14,3.25,522.77,0.4228,5.3421276322,V,V
4,20000005,5 Astraea (A845 XA),MBA,N,N,147,2461200.5,0.1876,2.577,2.093,...,141.45,359.38,181.48,1.11,6.95,106.699,0.274,16.806,S,S
5,20000006,6 Hebe (A847 NA),MBA,N,N,JPL 121,2461200.5,0.2023,2.426,1.935,...,138.61,239.73,44.72,0.976,5.62,185.18,0.2679,7.2745,S,S
6,20000007,7 Iris (A847 PA),MBA,N,N,JPL 144,2461200.5,0.2303,2.386,1.836,...,259.49,145.41,115.29,0.848,5.70,199.83,0.2766,7.139,S,S
7,20000008,8 Flora (A847 UA),MBA,N,N,152,2461200.5,0.1562,2.202,1.858,...,110.84,285.41,259.26,0.874,6.62,147.491,0.226,12.865,S,NaN
8,20000009,9 Metis (A848 HA),MBA,N,N,148,2461200.5,0.1225,2.387,2.094,...,68.87,5.93,252.62,1.11,6.18,190,0.118,5.079,S,NaN
9,20000010,10 Hygiea (A849 GA),MBA,N,N,JPL 129,2461200.5,0.1067,3.151,2.815,...,283.12,312.42,252.03,1.81,5.65,407.12,0.0717,13.828,C,C

In [20]:
numerical_features = ["epoch", "eccentricity", "semimajor_axis", "perihelion_distance", "inclination", "longitude_of_ascending_node", "argument_of_perihelion", "mean_anomaly", "minimum_orbit_intersection_distance", "absolute_magnitude", "diameter", "albedo", "rotation_period"]
categorical_features = ["spkid", "full_name", "class", "orbit_id", "spectral_type_T", "spectral_type_B"]

In [21]:
for features in numerical_features:
    df[features] = pd.to_numeric(df[features], errors="coerce")

In [22]:
df.dtypes

spkid                                    int64
full_name                                  str
class                                      str
neo_flag                                   str
pha_flag                                   str
orbit_id                                   str
epoch                                  float64
eccentricity                           float64
semimajor_axis                         float64
perihelion_distance                    float64
inclination                            float64
longitude_of_ascending_node            float64
argument_of_perihelion                 float64
mean_anomaly                           float64
minimum_orbit_intersection_distance    float64
absolute_magnitude                     float64
diameter                               float64
albedo                                 float64
rotation_period                        float64
spectral_type_T                            str
spectral_type_B                            str
dtype: object

#### we successfully converted the numerical data to required dtype

## Evaluating the uniqueness of the data

In [23]:
df.nunique()

spkid                                  1500
full_name                              1500
class                                     7
neo_flag                                  2
pha_flag                                  1
orbit_id                                190
epoch                                     1
eccentricity                           1152
semimajor_axis                          805
perihelion_distance                     966
inclination                            1059
longitude_of_ascending_node            1469
argument_of_perihelion                 1476
mean_anomaly                           1460
minimum_orbit_intersection_distance     348
absolute_magnitude                      558
diameter                               1461
albedo                                  503
rotation_period                        1455
spectral_type_T                         105
spectral_type_B                          24
dtype: int64

#### as we can see the name of the aesteroid in each row is unique as it matches with the number of spkid
#### spkid is the unique and permanent identifier given by JPL
#### as the 'name' element is more valuable, it is not necessary to keep the spkid
#### that said, orbit_id is not so unique and can contribute for analysis at later stage
#### as for other feature, spectral features are not that necessary for any predictive modeling and only helps in calculating diameter,
#### as they are missing in large quantity given the number of rows, we can remove them as well
#### likewise, spectral type T being a categorical variable has 105 unique element, upon encoding it won't contribute much

## Imputing values

In [24]:
df.isnull().sum()

spkid                                    0
full_name                                0
class                                    0
neo_flag                                 0
pha_flag                                 0
orbit_id                                 0
epoch                                    0
eccentricity                             0
semimajor_axis                           0
perihelion_distance                      0
inclination                              0
longitude_of_ascending_node              0
argument_of_perihelion                   0
mean_anomaly                             0
minimum_orbit_intersection_distance      0
absolute_magnitude                       0
diameter                                26
albedo                                  28
rotation_period                         16
spectral_type_T                        692
spectral_type_B                        878
dtype: int64

#### fill missing diameter using absolute magnitude and albedo
#### for this we need the albedo metric and absolute metric to be non-zero
#### we are using the scientific formula, wherever it is possible to fill the metric

In [25]:
mask = (
    df["diameter"].isna()
    & df["absolute_magnitude"].notna()
    & df["albedo"].notna()
    & (df["albedo"] > 0)
)

df.loc[mask, "diameter"] = (
    1329 * 10 ** (-df.loc[mask, "absolute_magnitude"] / 5)
    / np.sqrt(df.loc[mask, "albedo"])
)

#### in the same way, filling albedo

In [26]:
mask = (
    df["albedo"].isna()
    & df["absolute_magnitude"].notna()
    & df["diameter"].notna()
    & (df["diameter"] > 0)
)

df.loc[mask, "albedo"] = (
    1329 * 10 ** (-df.loc[mask, "absolute_magnitude"] / 5)
    / df.loc[mask, "diameter"]
) ** 2

#### In rows, where the corresponding necessary metric is null, we are not
#### able to determine the missing values using formula, in such case
#### we are filling our null values with medians

In [27]:
df["diameter"] = df["diameter"].fillna(df["diameter"].median())
df["albedo"] = df["albedo"].fillna(df["albedo"].median())
df["rotation_period"] = df["rotation_period"].fillna(df["rotation_period"].median())

In [28]:
df[["diameter", "albedo", "rotation_period"]].isna().sum()

diameter           0
albedo             0
rotation_period    0
dtype: int64

In [29]:
df.isnull().sum()

spkid                                    0
full_name                                0
class                                    0
neo_flag                                 0
pha_flag                                 0
orbit_id                                 0
epoch                                    0
eccentricity                             0
semimajor_axis                           0
perihelion_distance                      0
inclination                              0
longitude_of_ascending_node              0
argument_of_perihelion                   0
mean_anomaly                             0
minimum_orbit_intersection_distance      0
absolute_magnitude                       0
diameter                                 0
albedo                                   0
rotation_period                          0
spectral_type_T                        692
spectral_type_B                        878
dtype: int64

## Dropping unnecessary Features

#### as mentioned bedore, we will drop the identifier column - spkid
#### also we will drop spectral features, as most of the values are unknown given the number of data

In [30]:
unnecessary_features = ["spkid", "spectral_type_T", "spectral_type_B"]

df = df.drop(columns=unnecessary_features)

In [31]:
df.columns.tolist()

['full_name',
 'class',
 'neo_flag',
 'pha_flag',
 'orbit_id',
 'epoch',
 'eccentricity',
 'semimajor_axis',
 'perihelion_distance',
 'inclination',
 'longitude_of_ascending_node',
 'argument_of_perihelion',
 'mean_anomaly',
 'minimum_orbit_intersection_distance',
 'absolute_magnitude',
 'diameter',
 'albedo',
 'rotation_period']

## Standardization and Validation of data

In [39]:
measurements = ["epoch", "eccentricity", "semimajor_axis", "perihelion_distance", "inclination", "longitude_of_ascending_node", "argument_of_perihelion", "mean_anomaly", "minimum_orbit_intersection_distance", "absolute_magnitude", "diameter", "albedo", "rotation_period"]

for feature in measurements:
    print((df[feature] <= 0).sum())

0
0
0
0
0
0
0
0
0
0
0
0
0

#### numercical measurements shouldn't be negative as verified

### Engineered Features

In [40]:
df["orbital_period_years"] = df["semimajor_axis"] ** 1.5

#### orbital period years says how long the aesteroids take to orbit the Sun

In [41]:
df["aphelion_distance"] = (
    df["semimajor_axis"] * (1 + df["eccentricity"])
)

#### aphelion distance gives us the distance of the asteroid from the sun
#### it helps in comparing the perihelion distance

In [42]:
bins = [-np.inf, 0.1, 0.4, np.inf]
labels = ["circular", "moderate_eccentricity", "high_eccentricity"]
df["size_category"] = pd.cut(df["diameter"], bins=bins, labels=labels)

#### Binning is the process of converting the continous variables into discrete intervals
#### by binning the data into circular, moderate eccentricity, and high eccentricity helps in visualization

## Grouping and Aggregation

#### grouping and aggregation helps to summarize the information relatively easily
#### they form the basis for creating tables later on

In [46]:
class_summary = (
    df.groupby("class", dropna=False)
      .agg(
          asteroid_count=("full_name", "count"),
          average_diameter=("diameter", "mean"),
          median_diameter=("diameter", "median"),
          average_albedo=("albedo", "mean")
      )
      .reset_index()
)

print(class_summary)

  class  asteroid_count  average_diameter  median_diameter  average_albedo
0   AMO               5         20.078200          16.8400        0.219618
1   CEN               1         38.000000          38.0000        0.060000
2   IMB               6          6.374833           6.6325        0.567667
3   MBA            1344         54.534667          38.4500        0.148152
4   MCA              22         34.933045          40.6760        0.135186
5   OMB             110         81.863091          72.9515        0.072038
6   TJN              12        122.863167         116.2050        0.047917

#### this is class-wise information on data of aesteroids
#### this carries essential information, such as MBA class has higher number
#### Aesteroid of class TJN are significantly larger; larger doesn't always means more hazardous

In [49]:
risk_summary = (
    df.groupby(["neo_flag", "pha_flag"], dropna=False)
      .agg(
          asteroid_count=("full_name", "count"),
          median_diameter=("diameter", "median")
      )
      .reset_index()
)
print(risk_summary)

  neo_flag pha_flag  asteroid_count  median_diameter
0        N        N            1495           40.676
1        Y        N               5           16.840

##### the risk summary tells us in the data no aesteroids is potentially hazardous
##### the aesteroids which are near Earth has significantly smaller diameter