<a href="https://colab.research.google.com/github/Ku-shal9/Data_Analysis_wth_Python_module/blob/Assignment1_Kushal/practice_ques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 1: Read the CSV file

In [6]:
import pandas as pd

df = pd.read_csv("/content/pandas_dataset.csv")
shape_before = df.shape

df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

## Question 2: Renaming Columns

In [7]:
## converting to lowercase
df.columns = df.columns.str.lower()

## removing spaces and adding underscore
df.columns = df.columns.str.replace(' ', '_')
print("After: ", df.columns)

After:  Index(['order_id', 'customer_name', 'category', 'product', 'city', 'quantity',
       'unit_price', 'order_date', 'status', 'sales', 'profit', 'discount'],
      dtype='object')

## Question 3: Drop Unnecessary Rows

In [4]:
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [8]:
# dropping first empty row
df = df.drop([0])

# reset the index
df.reset_index(drop=True, inplace=True)

df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

## Question 4: Dropping unnecessary columns

In [5]:
df.drop(columns="customer_name", inplace=True)

"""
customer_name is kind of a unique element, meaning for every customer, there is a unique name that
doesn't contribute much to profit/loss analysis. If all values are unique, we cannot find any patterns whatsoever.

"""

df.head()

,order_id,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

## Question 5: Missing Values

In [ ]:
print(df.isnull().sum())

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
order_date       0
status           1
sales            3
profit           3
discount         3
dtype: int64

## Question 6: Handle Missing Values

### a. Drop rows based on column

In [ ]:
df = df.dropna(subset=['sales']).reset_index(drop=True) # droping rows will change indices thus it is necessary
print(df.isnull().sum())

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         0
unit_price       0
order_date       0
status           1
sales            0
profit           1
discount         1
dtype: int64

### b. Imputing

In [ ]:
df["profit"]=df["profit"].fillna(df["profit"].mean())
df["discount"]=df["discount"].fillna(df["discount"].median())
print(df.isnull().sum())

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
order_date       0
status           1
sales            0
profit           0
discount         0
dtype: int64

## Question 7: Handling missing categorical data

In [ ]:
df["customer_name"] = df["customer_name"].fillna("Unknown")
print(df.isnull().sum())

order_id         0
customer_name    0
category         0
product          0
city             1
quantity         1
unit_price       1
order_date       0
status           1
sales            0
profit           0
discount         0
dtype: int64

### Question 8: Duplicates

In [9]:
duplicate_values = df.duplicated(subset=["order_id"])

print("Number of duplicated values:", duplicate_values.sum())

before_removal = len(df)

df = df.drop_duplicates(subset=["order_id"])

duplicate_count = df.duplicated(subset=["order_id"]).sum()

after_removing = len(df)

df.reset_index(drop=True, inplace=True)

print("Number of duplicate values removed: ", before_removal-after_removing)

print("Number of duplicates remaining:", duplicate_count)

Number of duplicated values: 3
Number of duplicate values removed:  3
Number of duplicates remaining: 0

### Question 9: Filtering

In [ ]:
# unit_price is greater than 20,000.
df[df["unit_price"] > 20000]

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
1,1001,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000,34000.0,17000.0
5,1005,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000,11000.0,5500.0
7,1007,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000,10000.0,5000.0
12,1013,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000,11200.0,5600.0
16,1017,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,3/5/2026,Completed,22000,4400.0,1100.0

In [ ]:
# display customer_name, category, and status for orders where unit_price >
# 10,000 and status == "Completed".

df[(df["unit_price"] > 10000) & (df["status"] == "Completed")][["customer_name", "category", "status"]]

   customer_name     category     status
1          Aarav  Electronics  Completed
2           Sita    Furniture  Completed
7          Nabin    Furniture  Completed
12        Roshan  Electronics  Completed
16         Manoj    Furniture  Completed
18          Rita  Electronics  Completed
19        Bikash    Furniture  Completed

In [ ]:
# Create a new column called total_amount:
df["total_amount"] = df["quantity"] * df["unit_price"] - df["discount"]
df.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount,total_amount
0,order_id,customer_name,category,product,city,NaN,NaN,order_date,status,sales,7323.636364,825.0,NaN
1,1001,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000,34000.000000,17000.0,153000.0
2,1002,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000,3600.000000,900.0,17100.0
3,1003,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500,2700.000000,675.0,12825.0
4,1004,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000,2600.000000,650.0,12350.0

In [ ]:
# Create a column called customer_type based on quantity:
import numpy as np

df["customer_type"] = np.where(
    df["quantity"] >= 3,
    "Bulk Buyer",
    "Regular Buyer"
)

In [ ]:
shape_after = df.shape

print("Shape before: ", shape_before)
print("Shape after: ", shape_after)

Shape before:  (29, 12)
Shape after:  (21, 14)

In [ ]:
df.head(10)

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount,total_amount,customer_type
0,order_id,customer_name,category,product,city,NaN,NaN,order_date,status,sales,7323.636364,825.0,NaN,Regular Buyer
1,1001,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000,34000.000000,17000.0,153000.0,Regular Buyer
2,1002,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000,3600.000000,900.0,17100.0,Regular Buyer
3,1003,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500,2700.000000,675.0,12825.0,Bulk Buyer
4,1004,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000,2600.000000,650.0,12350.0,Regular Buyer
5,1005,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000,11000.000000,5500.0,49500.0,Regular Buyer
6,1006,Pragya,Books,Python Book,NaN,4.0,2200.0,1/22/2026,Completed,8800,1760.000000,440.0,8360.0,Bulk Buyer
7,1007,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000,10000.000000,5000.0,45000.0,Regular Buyer
8,1008,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,2/2/2026,Pending,22500,4500.000000,1125.0,21375.0,Bulk Buyer
9,1010,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,2/9/2026,Completed,7000,1400.000000,350.0,6650.0,Regular Buyer